using System.Numerics;

namespace Ball;

public readonly record struct Position(Vector2 Value);
public readonly record struct Velocity(Vector2 Value);
public readonly record struct Orientation(float Value);
public readonly record struct Scale(Vector2 Value);
public readonly record struct Model(int ID);
public readonly record struct BoundingBox(float X, float Y, float Width, float Height);
public readonly record struct Circle(float Radius);
public readonly record struct SolidCollision();
public readonly record struct HitBall();
public readonly record struct Player();
public readonly record struct Bounce();
public readonly record struct CanBeHit();
public readonly record struct HasGravity(float Scale);
public readonly record struct ResetBallOnHit();
public readonly record struct CanTakeDamageFromBall();
public readonly record struct CameraPosition(float Y);
public readonly record struct FollowsCamera(float Y);
public readonly record struct CameraFollows();
public readonly record struct UI();
public readonly record struct DestroyOnRestartGame();
public readonly record struct Life();
public readonly record struct FirstLife();
public readonly record struct HitPoints(int Value, int Max);
public readonly record struct Initialize();
public readonly record struct Score(int Current);
public readonly record struct HighScore(int Value);
public readonly record struct Meter(float Value, float Decay, float Scale);
public readonly record struct MoveTowardsPlayer(float Acceleration, float MaxVelocity);
public readonly record struct FillMeter(float Amount);
public readonly record struct AddGems(int Amount);
public readonly record struct AngularVelocity(float Value);
public readonly record struct Highlight();
public readonly record struct InvertColor();
public readonly record struct Flicker(float Rate);
public readonly record struct Invisible();
public readonly record struct Gems(int Current, int Total);
public readonly record struct Block(int GemReward);