using System.Numerics;

namespace Ball;

public readonly record struct Position(Vector2 Value);
public readonly record struct Velocity(Vector2 Value);
public readonly record struct Orientation(float Value);
public readonly record struct Scale(Vector2 Value);
public readonly record struct Model(int ID);
public readonly record struct BoundingBox(float X, float Y, float Width, float Height);
public readonly record struct Circle(float Radius);
public readonly record struct SolidCollision();
public readonly record struct HitBall();
public readonly record struct Player();
public readonly record struct Bounce(float Coefficient);
public readonly record struct CanBeHit();
public readonly record struct HasGravity(float Scale);
public readonly record struct DestroysBall();
public readonly record struct CanTakeDamage();
public readonly record struct CanDealDamageToBlock(int Amount);
public readonly record struct CameraPosition(float Y);
public readonly record struct FollowsCamera(float Y);
public readonly record struct CameraFollows();
public readonly record struct UI();
public readonly record struct WordWrap(int Max);
public readonly record struct HideOnMainMenu();
public readonly record struct MainMenu();
public readonly record struct WhilePaused();
public readonly record struct Depth(float Value);
public readonly record struct Lives(int Value);
public readonly record struct HitPoints(int Value, int Max);
public readonly record struct Initialize();
public readonly record struct Score(int Current);
public readonly record struct HighScore(int Value);
public readonly record struct Power(float Value, float Decay, float Scale);
public readonly record struct XP(int Current, int Target);
public readonly record struct Level(int Value);
public readonly record struct GivesXP(int Amount);
public readonly record struct MoveTowardsPlayer(float Acceleration, float MaxVelocity);
public readonly record struct FillMeter(float Amount);
public readonly record struct AddGems(int Amount);
public readonly record struct AngularVelocity(float Value);
public readonly record struct Highlight();
public readonly record struct InvertColor();
public readonly record struct Flicker(float Rate);
public readonly record struct Invisible();
public readonly record struct Gems(int Current, int Total);
public readonly record struct Block(int GemReward);
public readonly record struct DamageMultiplier(int Multiplier);
public readonly record struct Pause();
public readonly record struct KeepOpacityWhenPaused();
public readonly record struct Marquee(float Speed);
public readonly record struct PlayOnce(int AudioID, bool RandomizePitch = false);
public readonly record struct Alpha(byte A);
public readonly record struct Selected();
public readonly record struct Selector();
public readonly record struct DestroyOnStateTransition();
public readonly record struct DontDestroyOnNextTransition();
public readonly record struct GivesUpgrade();
public readonly record struct UpgradeOption(Upgrades Upgrade);
public readonly record struct DamageBlocksOnLostLife();
public readonly record struct DoubleDamageOnOneLife();
public readonly record struct PiercingBalls();
public readonly record struct BlocksSpawnWithLessHealth();
public readonly record struct DestroyedBlocksDamageNeighbors();
public readonly record struct Combo(int Value);
public readonly record struct ReviveWithOneHealth(bool Active);
public readonly record struct BarrierTakesExtraHit(bool Active);
public readonly record struct BlocksSpawnBonusBalls();
public readonly record struct BonusLives();
public readonly record struct GivesExtraLife();
public readonly record struct MoveBackAndForth(float Min, float Max, float Speed);
public readonly record struct Pulsate(Vector2 Scale, float Rate, float Amount);
public readonly record struct ExpandingEchoes(float Rate, float GrowthRate, float Lifetime);
public readonly record struct AnimationTimer(float Time);
public readonly record struct GrowOverTime(float Rate);
public readonly record struct ComboAddedToDamage();
public readonly record struct ComboText();
public readonly record struct FadeOut();
public readonly record struct SetHighScoreThisRun();
public readonly record struct Setting();
public readonly record struct SFXVolume(float Value);
public readonly record struct MusicVolume(float Value);
public readonly record struct Fullscreen(bool Value);
public readonly record struct EndScreen();